const mechRoutes = {
  signup: "/mech/signup",
  login: "/mech/login",
  veryfyOtp: "/mech/veryfy-otp",
  forgotPasswordMech: "/mech/forgot-password",
  updateNewPasswordMech: "/mech/update-newpassword",
  forgotVerifyOtpMech: "/mech/verify-forgot-otp",
  resendOtp: "/mech/resend-otp",
  resendOtp_forgetPassword_mechanic: "/mech/resendOtp_forgetPassword_mechanic",
  getAllMechanics: "/mech/getAllMechanics",
  getAllDevices: "/mech/getAllDevices",
  VerifyMechanic: "mech/verifyMechanic",
  getMechanicDetails: "mech/getMechanicDetails",
  getS3SingUrlForMechCredinential: "mech/getS3SingUrlForMechCredinential",
  getAllUserRegisteredServices: "mech/getAllUserRegisteredServices",
  getComplaintDetails: "mech/getComplaintDetails",
  getImageUrl: "mech/getImageUrl",
  updateWorkAssigned: "mech/updateWorkAssigned",
  getAllAcceptedServices: "mech/getAllAcceptedServices",
  getAllCompletedServices: "mech/getAllCompletedServices",
  updateComplaintStatus: "mech/updateComplaintStatus",
  editMechanic: "mech/editMechanic",
  createRoom: "mech/createRoom",
  updateWorkDetails: "mech/updateWorkDetails",
  addMechAddress: "mech/addMechAddress",
  editAddress: "/mech/editAddress",
  createRoute: "/mech/report",
  removeMechAddress: "/mech/handleRemoveMechAddress",
  getMechanicAddress: "/mech/getMechanicAddress",
  setDefaultAddress: "/mech/setDefaultAddress",
  logout: "/mech/logout",
};

export default mechRoutes;
