const userRoutes = {
  login: "/user/login",
  signup: "/user/registration",
  googleLogin: "/user/google-login",
  veryfyOtp: "/user/veryfy-otp",
  getTempUserData:"/user/getTempUserData",
  forgotPassword: "/user/forgot-password",
  forgotVerifyOtp: "/user/verify-forgot-otp",
  updateNewPassword: "/user/update-newpassword",
  resendOtp: "/user/resend-otp",
  logout: "/user/logout",
  getProfile: "/user/profile",
  editUser:"/user/editUser",
  addAddress:"/user/addAddress",
  editAddress:"/user/editAddress",
  setDefaultAddress:"/user/setDefaultAddress",
  registerService:"/user/registerService",
  getAllServices:"/user/getAllServices",
  getAllUserRegisteredServices:"/user/getAllUserRegisteredServices",
  getUserRegisteredServiceDetailsById:"/user/getUserRegisteredServiceDetailsById",
  getMechanicDetails:"/user/getMechanicDetails",
  getService:"/user/getService/",
  getImageUrl: "/user/getImageUrl",
  getMessages:"/user/getMessages",
  handlePayment:"/user/handlePayment",
  successPayment:"/user/successPayment",
};

export default userRoutes;
